package cPresentacion;

import cEntidad.NotaEntidad;
import cNegocio.NotaNegocio;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RegistroNotas extends javax.swing.JInternalFrame {
    private NotaNegocio notaNegocio;
    private DefaultTableModel tableModel;
    /**
     * Creates new form RegistroNotas
     */
    public RegistroNotas() {
        initComponents();
        notaNegocio = new NotaNegocio();
        tableModel = (DefaultTableModel) tableNotas.getModel();
        
        // Agregar títulos de columnas
        String[] columnNames = {"ID", "Materia", "Nota 1", "Nota 2", "Nota 3", "Promedio", "Fecha Registro"};
        tableModel.setColumnIdentifiers(columnNames);
        
       // Mostrar información almacenada en la tabla
        listarNotas();
        
        // Agregar botón "Eliminar"
        btnEliminar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int fila = tableNotas.getSelectedRow();
                if (fila!= -1) {
                    String idAlumno = (String) tableModel.getValueAt(fila, 0);
                    String materia = (String) tableModel.getValueAt(fila, 1);

                    // Diálogo de confirmación
                    int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la nota de " + materia + " del alumno " + idAlumno + "?", "Eliminar Nota", JOptionPane.YES_NO_OPTION);

                    if (respuesta == JOptionPane.YES_OPTION) {
                        notaNegocio.eliminarNota(idAlumno, materia);
                        tableModel.removeRow(fila);
                    }
                }
            }
        });
    }
    
    private void listarNotas() {
        List<NotaEntidad> notas = notaNegocio.listarNotas();
        for (NotaEntidad nota : notas) {
            Object[] row = new Object[] {
                nota.getIdAlumno(),
                nota.getMateria(),
                nota.getNota1(),
                nota.getNota2(),
                nota.getNota3(),
                nota.getPromedio(),
                nota.getFechaRegistro()
            };
            tableModel.addRow(row);
        }
    }
    
    private void cancelarNota() {
    // Revertir cambios en la interfaz de usuario
    txtIdAlumno.setText("");
    txtMateria.setText("");
    txtNota1.setText("");
    txtNota2.setText("");
    txtNota3.setText("");
    txtPromedio.setText("");
    txtFechaRegistro.setText("");

    // Revertir cambios en la lógica de negocio
    notaNegocio.cancelarNota();
}
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdAlumno = new javax.swing.JTextField();
        txtMateria = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        txtNota1 = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNota3 = new javax.swing.JTextField();
        txtPromedio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFechaRegistro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNotas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("idAlumno ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel3.setText("materia ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setText("nota1 ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel5.setText("promedio ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 191, -1, -1));
        getContentPane().add(txtIdAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 121, -1));
        getContentPane().add(txtMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 120, -1));
        getContentPane().add(txtNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 150, 70, -1));
        getContentPane().add(txtNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, -1));

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel6.setText("nota3 ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel7.setText("nota2 ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));
        getContentPane().add(txtNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 80, -1));
        getContentPane().add(txtPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 188, 139, -1));

        jLabel8.setText("fechaRegistro ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 225, -1, -1));
        getContentPane().add(txtFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 222, 139, -1));

        tableNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableNotas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 0, 393, 419));

        jLabel1.setText("REGISTRO DE NOTAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        btnEliminar.setText("ELIMINAR");
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelarNota();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String idAlumno = txtIdAlumno.getText();
        String materia = txtMateria.getText();
        String nota1 = txtNota1.getText();
        String nota2 = txtNota2.getText();
        String nota3 = txtNota3.getText();
        String promedio = txtPromedio.getText();
        String fechaRegistro = txtFechaRegistro.getText();

        notaNegocio.registrarNota(idAlumno, materia, nota1, nota2, nota3, promedio, fechaRegistro);

        // Agregar datos a la tabla
        Object[] row = new Object[] {idAlumno, materia, nota1, nota2, nota3, promedio, fechaRegistro};
        tableModel.addRow(row);
        
        
        
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNotas;
    private javax.swing.JTextField txtFechaRegistro;
    private javax.swing.JTextField txtIdAlumno;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    private javax.swing.JTextField txtPromedio;
    // End of variables declaration//GEN-END:variables
}
